export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const ERROR_INGREDIENTS = "ERROR_INGREDIENTS";

export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESSFUL = "ORDER_SUCCESSFUL";
export const ORDER_FAILED = "ORDER_FAILED";
export const PURCHASED_REDIRECTION = "PURCHASED_REDIRECTION";

export const FETCHING_ORDERS = "FETCHING_ORDERS";

export const START_AUTH = "START_AUTH";
export const SUCCESS_AUTH = "SUCCESS_AUTH";
export const FAILED_AUTH = "FAILED_AUTH";
export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const LOGOUT_EMPTY_ORDERS = "LOGOUT_EMPTY_ORDERS";
