export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';

export const ORDER_START = 'ORDER_START';
export const ORDER_SUCCESSFUL = 'ORDER_SUCCESSFUL';
export const ORDER_FAILED = 'ORDER_FAILED';